version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}sales-api
    build:
      context: src
      dockerfile: Api/Dockerfile
    environment:
    # Nice conversation starter :)
    # These values are secrets and should not be handled like this
      - "ConnectionStrings__DefaultConnection=Server=db;Database=SalesDb;User=sa;Password=MyPassword123;MultipleActiveResultSets=true"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "4200:4200"
      - "4201:4201"
    depends_on:
      - db
    restart: on-failure
# Nice conversation starter :)
# How to handle DB in the containerized world
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=MyPassword123"
      - "ACCEPT_EULA=Y"